const lastName = "田中";
const firstName = "一郎";
const fullName = lastName + " " + firstName;
const myAge = 27;
const friendAge = 25;
const totalAge = myAge + friendAge;
const numberOfDays = totalAge * 365;
const numberOfChildren = 3;
const numberOfCake = 10;
const numberOfCakesByChild = numberOfCake / numberOfChildren;
const numberOfRestOfCakes = numberOfCake % numberOfChildren;
console.log(lastName);
console.log(firstName); 
console.log(fullName);
console.log(myAge);
console.log(friendAge);
console.log(totalAge);
console.log(numberOfDays);
console.log(numberOfChildren);
console.log(numberOfCake);
console.log(numberOfCakesByChild);
console.log(numberOfRestOfCakes);